title: 류동훈 (Patrick Ryu) Blog
author: dong149
email: donghoon149@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  류동훈(Patrick Ryu)의 개인 블로그입니다. 
  저의 이야기와 서비스 개발/기획/마케팅 경험들에 관련된 정보들을 담은 블로그입니다.
show_excerpts: true # set to true to show excerpts on the homepage
url: https://dong149.github.io
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Patrick Ryu
  tagline: Project Manager. Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: dong149
  # generate social links in footer
  social_links:
    twitter:
    github: dong149
    linkedIn: in/patrick-ryu-4a1b46199
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
